// Auto-generated from taxonomy.table by the taxonomy import pipeline.
// Do not hand-edit; regenerate from uma.guide data via the daily sync job.
import type { TaxonomyTerm } from './types';

export const taxonomyTerms: TaxonomyTerm[] = [
  { id: 1, term: "umamusume", tier: "strong", category: "game" },
  { id: 2, term: "umamusume: pretty derby", tier: "strong", category: "game" },
  { id: 3, term: "ウマ娘", tier: "strong", category: "game" },
  { id: 4, term: "ウマ娘 プリティーダービー", tier: "strong", category: "game" },
  { id: 5, term: "pretty derby", tier: "strong", category: "game" },
  { id: 6, term: "special week", tier: "strong", category: "character" },
  { id: 7, term: "スペシャルウィーク", tier: "strong", category: "character" },
  { id: 8, term: "silence suzuka", tier: "strong", category: "character" },
  { id: 9, term: "サイレンススズカ", tier: "strong", category: "character" },
  { id: 10, term: "tokai teio", tier: "strong", category: "character" },
  { id: 11, term: "トウカイテイオー", tier: "strong", category: "character" },
  { id: 12, term: "mejiro mcqueen", tier: "strong", category: "character" },
  { id: 13, term: "メジロマックイーン", tier: "strong", category: "character" },
  { id: 14, term: "oguri cap", tier: "strong", category: "character" },
  { id: 15, term: "オグリキャップ", tier: "strong", category: "character" },
  { id: 16, term: "rice shower", tier: "strong", category: "character" },
  { id: 17, term: "ライスシャワー", tier: "strong", category: "character" },
  { id: 18, term: "gold ship", tier: "strong", category: "character" },
  { id: 19, term: "ゴールドシップ", tier: "strong", category: "character" },
  { id: 20, term: "daiwa scarlet", tier: "strong", category: "character" },
  { id: 21, term: "ダイワスカーレット", tier: "strong", category: "character" },
  { id: 22, term: "t.m. opera o", tier: "strong", category: "character" },
  { id: 23, term: "el condor pasa", tier: "strong", category: "character" },
  { id: 24, term: "エルコンドルパサー", tier: "strong", category: "character" },
  { id: 25, term: "champions meeting", tier: "strong", category: "pvp-mode" },
  { id: 26, term: "チャンピオンズミーティング", tier: "strong", category: "pvp-mode" },
  { id: 27, term: "loh", tier: "strong", category: "pvp-mode" },
  { id: 28, term: "league of heroes", tier: "strong", category: "pvp-mode" },
  { id: 29, term: "grand live", tier: "strong", category: "scenario" },
  { id: 30, term: "グランドライブ", tier: "strong", category: "scenario" },
  { id: 31, term: "grand concert", tier: "strong", category: "scenario" },
  { id: 32, term: "make debut", tier: "strong", category: "scenario" },
  { id: 33, term: "メイクデビュー", tier: "strong", category: "scenario" },
  { id: 34, term: "trackblazer", tier: "strong", category: "scenario" },
  { id: 35, term: "unity cup", tier: "strong", category: "scenario" },
  { id: 36, term: "team trials", tier: "strong", category: "pvp-mode" },
  { id: 37, term: "twinkle series", tier: "strong", category: "pvp-mode" },
  { id: 38, term: "growth rate", tier: "strong", category: "mechanic" },
  { id: 39, term: "aptitude", tier: "strong", category: "mechanic" },
  { id: 40, term: "support card", tier: "strong", category: "card" },
  { id: 41, term: "支持カード", tier: "strong", category: "card" },
  { id: 42, term: "unique skill", tier: "strong", category: "skill" },
  { id: 43, term: "固有スキル", tier: "strong", category: "skill" },
  { id: 44, term: "factor", tier: "strong", category: "mechanic" },
  { id: 45, term: "inheritance", tier: "strong", category: "mechanic" },
  { id: 46, term: "uma.guide", tier: "strong", category: "tool" },
  { id: 47, term: "ura", tier: "strong", category: "scenario" },
  { id: 48, term: "tracen", tier: "strong", category: "game" },
  { id: 49, term: "spark", tier: "weak", category: "mechanic", note: "ambiguous: also electrical/verb" },
  { id: 50, term: "race", tier: "weak", category: "mechanic", note: "ambiguous: common English" },
  { id: 51, term: "long", tier: "weak", category: "distance", note: "ambiguous: common English" },
  { id: 52, term: "grade", tier: "weak", category: "race-tier", note: "ambiguous: common English" },
  { id: 53, term: "cm", tier: "weak", category: "pvp-mode", note: "abbreviation for Champions Meeting, also 'centimeter'" },
  { id: 54, term: "mud", tier: "weak", category: "surface", note: "ambiguous" },
  { id: 55, term: "turf", tier: "weak", category: "surface", note: "ambiguous" },
  { id: 56, term: "dirt", tier: "weak", category: "surface", note: "ambiguous" },
  { id: 57, term: "maruzensky", tier: "strong", category: "character" },
  { id: 58, term: "fuji kiseki", tier: "strong", category: "character" },
  { id: 59, term: "vodka", tier: "strong", category: "character" },
  { id: 60, term: "taiki shuttle", tier: "strong", category: "character" },
  { id: 61, term: "grass wonder", tier: "strong", category: "character" },
  { id: 62, term: "hishi amazon", tier: "strong", category: "character" },
  { id: 63, term: "narita brian", tier: "strong", category: "character" },
  { id: 64, term: "symboli rudolf", tier: "strong", category: "character" },
  { id: 65, term: "air groove", tier: "strong", category: "character" },
  { id: 66, term: "agnes digital", tier: "strong", category: "character" },
  { id: 67, term: "seiun sky", tier: "strong", category: "character" },
  { id: 68, term: "tamamo cross", tier: "strong", category: "character" },
  { id: 69, term: "fine motion", tier: "strong", category: "character" },
  { id: 70, term: "biwa hayahide", tier: "strong", category: "character" },
  { id: 71, term: "mayano top gun", tier: "strong", category: "character" },
  { id: 72, term: "manhattan cafe", tier: "strong", category: "character" },
  { id: 73, term: "mihono bourbon", tier: "strong", category: "character" },
  { id: 74, term: "mejiro ryan", tier: "strong", category: "character" },
  { id: 75, term: "hishi akebono", tier: "strong", category: "character" },
  { id: 76, term: "yukino bijin", tier: "strong", category: "character" },
  { id: 77, term: "ines fujin", tier: "strong", category: "character" },
  { id: 78, term: "agnes tachyon", tier: "strong", category: "character" },
  { id: 79, term: "admire vega", tier: "strong", category: "character" },
  { id: 80, term: "inari one", tier: "strong", category: "character" },
  { id: 81, term: "winning ticket", tier: "strong", category: "character" },
  { id: 82, term: "air shakur", tier: "strong", category: "character" },
  { id: 83, term: "eishin flash", tier: "strong", category: "character" },
  { id: 84, term: "curren chan", tier: "strong", category: "character" },
  { id: 85, term: "kawakami princess", tier: "strong", category: "character" },
  { id: 86, term: "gold city", tier: "strong", category: "character" },
  { id: 87, term: "sakura bakushin o", tier: "strong", category: "character" },
  { id: 88, term: "seeking the pearl", tier: "strong", category: "character" },
  { id: 89, term: "sweep tosho", tier: "strong", category: "character" },
  { id: 90, term: "super creek", tier: "strong", category: "character" },
  { id: 91, term: "smart falcon", tier: "strong", category: "character" },
  { id: 92, term: "tosen jordan", tier: "strong", category: "character" },
  { id: 93, term: "narita taishin", tier: "strong", category: "character" },
  { id: 94, term: "nishino flower", tier: "strong", category: "character" },
  { id: 95, term: "haru urara", tier: "strong", category: "character" },
  { id: 96, term: "bamboo memory", tier: "strong", category: "character" },
  { id: 97, term: "matikanefukukitaru", tier: "strong", category: "character" },
  { id: 98, term: "meisho doto", tier: "strong", category: "character" },
  { id: 99, term: "mejiro dober", tier: "strong", category: "character" },
  { id: 100, term: "nice nature", tier: "strong", category: "character" },
  { id: 101, term: "king halo", tier: "strong", category: "character" },
  { id: 102, term: "matikanetannhauser", tier: "strong", category: "character" },
  { id: 103, term: "mejiro palmer", tier: "strong", category: "character" },
  { id: 104, term: "satono diamond", tier: "strong", category: "character" },
  { id: 105, term: "kitasan black", tier: "strong", category: "character" },
  { id: 106, term: "sakura chiyono o", tier: "strong", category: "character" },
  { id: 107, term: "mejiro ardan", tier: "strong", category: "character" },
  { id: 108, term: "yaeno muteki", tier: "strong", category: "character" },
  { id: 109, term: "mejiro bright", tier: "strong", category: "character" },
  { id: 110, term: "copano rickey", tier: "strong", category: "character" },
  { id: 111, term: "warning shot!", tier: "strong", category: "skill" },
  { id: 112, term: "xceleration", tier: "strong", category: "skill" },
  { id: 113, term: "red ace", tier: "strong", category: "skill" },
  { id: 114, term: "focused mind", tier: "strong", category: "skill" },
  { id: 115, term: "corazón ☆ ardiente", tier: "strong", category: "skill" },
  { id: 116, term: "empress's pride", tier: "strong", category: "skill" },
  { id: 117, term: "1st place kiss☆", tier: "strong", category: "skill" },
  { id: 118, term: "feel the burn!", tier: "strong", category: "skill" },
  { id: 119, term: "introduction to physiology", tier: "strong", category: "skill" },
  { id: 120, term: "v is for victory!", tier: "strong", category: "skill" },
  { id: 121, term: "class rep + speed = bakushin", tier: "strong", category: "skill" },
  { id: 122, term: "clear heart", tier: "strong", category: "skill" },
  { id: 123, term: "super-duper stoked", tier: "strong", category: "skill" },
  { id: 124, term: "luck be with me!", tier: "strong", category: "skill" },
  { id: 125, term: "i can win sometimes, right?", tier: "strong", category: "skill" },
  { id: 126, term: "call me king", tier: "strong", category: "skill" },
  { id: 127, term: "ready, go!", tier: "strong", category: "skill" },
  { id: 128, term: "shooting star", tier: "strong", category: "skill" },
  { id: 129, term: "the view from the lead is mine!", tier: "strong", category: "skill" },
  { id: 130, term: "sky-high teio step", tier: "strong", category: "skill" },
  { id: 131, term: "red shift/lp1211-m", tier: "strong", category: "skill" },
  { id: 132, term: "lights of vaudeville", tier: "strong", category: "skill" },
  { id: 133, term: "triumphant pulse", tier: "strong", category: "skill" },
  { id: 134, term: "anchors aweigh!", tier: "strong", category: "skill" },
  { id: 135, term: "cut and drive!", tier: "strong", category: "skill" },
  { id: 136, term: "resplendent red ace", tier: "strong", category: "skill" },
  { id: 137, term: "shooting for victory!", tier: "strong", category: "skill" },
  { id: 138, term: "where there's a will, there's a way", tier: "strong", category: "skill" },
  { id: 139, term: "you and me! one-on-one!", tier: "strong", category: "skill" },
  { id: 140, term: "the duty of dignity calls", tier: "strong", category: "skill" },
  { id: 141, term: "victoria por plancha ☆", tier: "strong", category: "skill" },
  { id: 142, term: "this dance is for vittoria!", tier: "strong", category: "skill" },
  { id: 143, term: "shadow break", tier: "strong", category: "skill" },
  { id: 144, term: "behold thine emperor's divine might", tier: "strong", category: "skill" },
  { id: 145, term: "blazing pride", tier: "strong", category: "skill" },
  { id: 146, term: "omg! (ﾟ∀ﾟ) the final sprint! ☆", tier: "strong", category: "skill" },
  { id: 147, term: "angling and scheming", tier: "strong", category: "skill" },
  { id: 148, term: "white lightning comin' through!", tier: "strong", category: "skill" },
  { id: 149, term: "fairy tale", tier: "strong", category: "skill" },
  { id: 150, term: "∴win q.e.d.", tier: "strong", category: "skill" },
  { id: 151, term: "flashy☆landing", tier: "strong", category: "skill" },
  { id: 152, term: "chasing after you", tier: "strong", category: "skill" },
  { id: 153, term: "g00 1st. f∞;", tier: "strong", category: "skill" },
  { id: 154, term: "let's pump some iron!", tier: "strong", category: "skill" },
  { id: 155, term: "yummy☆speed!", tier: "strong", category: "skill" },
  { id: 156, term: "snow bright, snow flight", tier: "strong", category: "skill" },
  { id: 157, term: "blue rose closer", tier: "strong", category: "skill" },
  { id: 158, term: "all charged! it's go time!", tier: "strong", category: "skill" },
  { id: 159, term: "u=ma2", tier: "strong", category: "skill" },
  { id: 160, term: "shooting star of dioskouroi", tier: "strong", category: "skill" },
  { id: 161, term: "now we're cruisin'!", tier: "strong", category: "skill" },
  { id: 162, term: "our ticket to win!", tier: "strong", category: "skill" },
  { id: 163, term: "trigger:beat", tier: "strong", category: "skill" },
  { id: 164, term: "schwarzes schwert", tier: "strong", category: "skill" },
  { id: 165, term: "#lookatcurren", tier: "strong", category: "skill" },
  { id: 166, term: "a princess must seize victory!", tier: "strong", category: "skill" },
  { id: 167, term: "keep it real.", tier: "strong", category: "skill" },
  { id: 168, term: "genius x bakushin = victory", tier: "strong", category: "skill" },
  { id: 169, term: "i'm possible!", tier: "strong", category: "skill" },
  { id: 170, term: "victory belongs to me—strelitzia! ☆", tier: "strong", category: "skill" },
  { id: 171, term: "pure heart", tier: "strong", category: "skill" },
  { id: 172, term: "sparkly☆stardom", tier: "strong", category: "skill" },
  { id: 173, term: "pop & polish", tier: "strong", category: "skill" },
  { id: 174, term: "nemesis", tier: "strong", category: "skill" },
  { id: 175, term: "budding blossom", tier: "strong", category: "skill" },
  { id: 176, term: "super-duper climax", tier: "strong", category: "skill" },
  { id: 177, term: "red-hot discipline!", tier: "strong", category: "skill" },
  { id: 178, term: "i see victory in my future!", tier: "strong", category: "skill" },
  { id: 179, term: "i never goof up!", tier: "strong", category: "skill" },
  { id: 180, term: "moving past, and beyond", tier: "strong", category: "skill" },
  { id: 181, term: "just a little farther!", tier: "strong", category: "skill" },
  { id: 182, term: "prideful king", tier: "strong", category: "skill" },
  { id: 183, term: "go, go, mun!", tier: "strong", category: "skill" },
  { id: 184, term: "keep pushing ahead", tier: "strong", category: "skill" },
  { id: 185, term: "eternal encompassing shine", tier: "strong", category: "skill" },
  { id: 186, term: "victory cheer!", tier: "strong", category: "skill" },
  { id: 187, term: "ambition to surpass the sakura", tier: "strong", category: "skill" },
  { id: 188, term: "a lifelong dream, a moment's flight", tier: "strong", category: "skill" },
  { id: 189, term: "peerless dance of flowering flames", tier: "strong", category: "skill" },
  { id: 190, term: "lovely spring breeze", tier: "strong", category: "skill" },
  { id: 191, term: "luck runs my way", tier: "strong", category: "skill" },
  { id: 192, term: "shine on, tomakomai! ☆", tier: "strong", category: "skill" },
  { id: 193, term: "dazzl'n ♪ diver", tier: "strong", category: "skill" },
  { id: 194, term: "certain victory", tier: "strong", category: "skill" },
  { id: 195, term: "a kiss for courage", tier: "strong", category: "skill" },
  { id: 196, term: "ravissant", tier: "strong", category: "skill" },
  { id: 197, term: "festive miracle", tier: "strong", category: "skill" },
  { id: 198, term: "564 escapades", tier: "strong", category: "skill" },
  { id: 199, term: "joyful voyage!", tier: "strong", category: "skill" },
  { id: 200, term: "superior heal", tier: "strong", category: "skill" },
  { id: 201, term: "legacy of the strong", tier: "strong", category: "skill" },
  { id: 202, term: "condor's fury", tier: "strong", category: "skill" },
  { id: 203, term: "barcarole of blessings", tier: "strong", category: "skill" },
  { id: 204, term: "arrows whistle, shadows disperse", tier: "strong", category: "skill" },
  { id: 205, term: "eternal moments", tier: "strong", category: "skill" },
  { id: 206, term: "the moe aaaa thanks for my life", tier: "strong", category: "skill" },
  { id: 207, term: "break it down!", tier: "strong", category: "skill" },
  { id: 208, term: "best day ever", tier: "strong", category: "skill" },
  { id: 209, term: "presents from x", tier: "strong", category: "skill" },
  { id: 210, term: "flowery☆maneuver", tier: "strong", category: "skill" },
  { id: 211, term: "operation cacao", tier: "strong", category: "skill" },
  { id: 212, term: "every rose has its fangs", tier: "strong", category: "skill" },
  { id: 213, term: "ticket to your dreams!", tier: "strong", category: "skill" },
  { id: 214, term: "guten appetit ♪", tier: "strong", category: "skill" },
  { id: 215, term: "one true color", tier: "strong", category: "skill" },
  { id: 216, term: "dancing in the leaves", tier: "strong", category: "skill" },
  { id: 217, term: "give mummy a hug ♡", tier: "strong", category: "skill" },
  { id: 218, term: "α-star*", tier: "strong", category: "skill" },
  { id: 219, term: "hephaestus", tier: "strong", category: "skill" },
  { id: 220, term: "114th time's the charm", tier: "strong", category: "skill" },
  { id: 221, term: "bountiful harvest", tier: "strong", category: "skill" },
  { id: 222, term: "spooky, scary, happy", tier: "strong", category: "skill" },
  { id: 223, term: "wherever this wonder leads", tier: "strong", category: "skill" },
  { id: 224, term: "go☆go☆goal!", tier: "strong", category: "skill" },
  { id: 225, term: "louder! tracen cheer!", tier: "strong", category: "skill" },
  { id: 226, term: "dreams donned with pride!", tier: "strong", category: "skill" },
  { id: 227, term: "your smile sparkles as the waves", tier: "strong", category: "skill" },
  { id: 228, term: "right-handed ◎", tier: "strong", category: "skill" },
  { id: 229, term: "right-handed ○", tier: "strong", category: "skill" },
  { id: 230, term: "right-handed ×", tier: "strong", category: "skill" },
  { id: 231, term: "right-handed demon", tier: "strong", category: "skill" },
  { id: 232, term: "left-handed ◎", tier: "strong", category: "skill" },
  { id: 233, term: "left-handed ○", tier: "strong", category: "skill" },
  { id: 234, term: "left-handed ×", tier: "strong", category: "skill" },
  { id: 235, term: "tokyo racecourse ◎", tier: "strong", category: "skill" },
  { id: 236, term: "tokyo racecourse ○", tier: "strong", category: "skill" },
  { id: 237, term: "tokyo racecourse ×", tier: "strong", category: "skill" },
  { id: 238, term: "nakayama racecourse ◎", tier: "strong", category: "skill" },
  { id: 239, term: "nakayama racecourse ○", tier: "strong", category: "skill" },
  { id: 240, term: "nakayama racecourse ×", tier: "strong", category: "skill" },
  { id: 241, term: "hanshin racecourse ◎", tier: "strong", category: "skill" },
  { id: 242, term: "hanshin racecourse ○", tier: "strong", category: "skill" },
  { id: 243, term: "hanshin racecourse ×", tier: "strong", category: "skill" },
  { id: 244, term: "kyoto racecourse ◎", tier: "strong", category: "skill" },
  { id: 245, term: "kyoto racecourse ○", tier: "strong", category: "skill" },
  { id: 246, term: "kyoto racecourse ×", tier: "strong", category: "skill" },
  { id: 247, term: "yodo invicta", tier: "strong", category: "skill" },
  { id: 248, term: "chukyo racecourse ◎", tier: "strong", category: "skill" },
  { id: 249, term: "chukyo racecourse ○", tier: "strong", category: "skill" },
  { id: 250, term: "chukyo racecourse ×", tier: "strong", category: "skill" },
  { id: 251, term: "sapporo racecourse ◎", tier: "strong", category: "skill" },
  { id: 252, term: "sapporo racecourse ○", tier: "strong", category: "skill" },
  { id: 253, term: "sapporo racecourse ×", tier: "strong", category: "skill" },
  { id: 254, term: "hakodate racecourse ◎", tier: "strong", category: "skill" },
  { id: 255, term: "hakodate racecourse ○", tier: "strong", category: "skill" },
  { id: 256, term: "hakodate racecourse ×", tier: "strong", category: "skill" },
  { id: 257, term: "fukushima racecourse ◎", tier: "strong", category: "skill" },
  { id: 258, term: "fukushima racecourse ○", tier: "strong", category: "skill" },
  { id: 259, term: "fukushima racecourse ×", tier: "strong", category: "skill" },
  { id: 260, term: "niigata racecourse ◎", tier: "strong", category: "skill" },
  { id: 261, term: "niigata racecourse ○", tier: "strong", category: "skill" },
  { id: 262, term: "niigata racecourse ×", tier: "strong", category: "skill" },
  { id: 263, term: "kokura racecourse ◎", tier: "strong", category: "skill" },
  { id: 264, term: "kokura racecourse ○", tier: "strong", category: "skill" },
  { id: 265, term: "kokura racecourse ×", tier: "strong", category: "skill" },
  { id: 266, term: "standard distance ◎", tier: "strong", category: "skill" },
  { id: 267, term: "standard distance ○", tier: "strong", category: "skill" },
  { id: 268, term: "standard distance ×", tier: "strong", category: "skill" },
  { id: 269, term: "non-standard distance ◎", tier: "strong", category: "skill" },
  { id: 270, term: "non-standard distance ○", tier: "strong", category: "skill" },
  { id: 271, term: "non-standard distance ×", tier: "strong", category: "skill" },
  { id: 272, term: "firm conditions ◎", tier: "strong", category: "skill" },
  { id: 273, term: "firm conditions ○", tier: "strong", category: "skill" },
  { id: 274, term: "firm conditions ×", tier: "strong", category: "skill" },
  { id: 275, term: "firm course menace", tier: "strong", category: "skill" },
  { id: 276, term: "wet conditions ◎", tier: "strong", category: "skill" },
  { id: 277, term: "wet conditions ○", tier: "strong", category: "skill" },
  { id: 278, term: "wet conditions ×", tier: "strong", category: "skill" },
  { id: 279, term: "spring runner ◎", tier: "strong", category: "skill" },
  { id: 280, term: "spring runner ○", tier: "strong", category: "skill" },
  { id: 281, term: "spring runner ×", tier: "strong", category: "skill" },
  { id: 282, term: "spring spectacle", tier: "strong", category: "skill" },
  { id: 283, term: "summer runner ◎", tier: "strong", category: "skill" },
  { id: 284, term: "summer runner ○", tier: "strong", category: "skill" },
  { id: 285, term: "summer runner ×", tier: "strong", category: "skill" },
  { id: 286, term: "fall runner ◎", tier: "strong", category: "skill" },
  { id: 287, term: "fall runner ○", tier: "strong", category: "skill" },
  { id: 288, term: "fall runner ×", tier: "strong", category: "skill" },
  { id: 289, term: "fall frenzy", tier: "strong", category: "skill" },
  { id: 290, term: "winter runner ◎", tier: "strong", category: "skill" },
  { id: 291, term: "winter runner ○", tier: "strong", category: "skill" },
  { id: 292, term: "winter runner ×", tier: "strong", category: "skill" },
  { id: 293, term: "sunny days ◎", tier: "strong", category: "skill" },
  { id: 294, term: "sunny days ○", tier: "strong", category: "skill" },
  { id: 295, term: "cloudy days ◎", tier: "strong", category: "skill" },
  { id: 296, term: "cloudy days ○", tier: "strong", category: "skill" },
  { id: 297, term: "rainy days ◎", tier: "strong", category: "skill" },
  { id: 298, term: "rainy days ○", tier: "strong", category: "skill" },
  { id: 299, term: "rainy days ×", tier: "strong", category: "skill" },
  { id: 300, term: "snowy days ◎", tier: "strong", category: "skill" },
  { id: 301, term: "snowy days ○", tier: "strong", category: "skill" },
  { id: 302, term: "inner post proficiency ◎", tier: "strong", category: "skill" },
  { id: 303, term: "inner post proficiency ○", tier: "strong", category: "skill" },
  { id: 304, term: "inner post averseness", tier: "strong", category: "skill" },
  { id: 305, term: "outer post proficiency ◎", tier: "strong", category: "skill" },
  { id: 306, term: "outer post proficiency ○", tier: "strong", category: "skill" },
  { id: 307, term: "outer post averseness", tier: "strong", category: "skill" },
  { id: 308, term: "maverick ◎", tier: "strong", category: "skill" },
  { id: 309, term: "maverick ○", tier: "strong", category: "skill" },
  { id: 310, term: "competitive spirit ◎", tier: "strong", category: "skill" },
  { id: 311, term: "competitive spirit ○", tier: "strong", category: "skill" },
  { id: 312, term: "wallflower", tier: "strong", category: "skill" },
  { id: 313, term: "target in sight ◎", tier: "strong", category: "skill" },
  { id: 314, term: "target in sight ○", tier: "strong", category: "skill" },
  { id: 315, term: "long shot ◎", tier: "strong", category: "skill" },
  { id: 316, term: "long shot ○", tier: "strong", category: "skill" },
  { id: 317, term: "g1 averseness", tier: "strong", category: "skill" },
  { id: 318, term: "paddock fright", tier: "strong", category: "skill" },
  { id: 319, term: "professor of curvature", tier: "strong", category: "skill" },
  { id: 320, term: "corner adept ○", tier: "strong", category: "skill" },
  { id: 321, term: "corner adept ×", tier: "strong", category: "skill" },
  { id: 322, term: "corner connoisseur", tier: "strong", category: "skill" },
  { id: 323, term: "corner acceleration ○", tier: "strong", category: "skill" },
  { id: 324, term: "corner acceleration ×", tier: "strong", category: "skill" },
  { id: 325, term: "swinging maestro", tier: "strong", category: "skill" },
  { id: 326, term: "corner recovery ○", tier: "strong", category: "skill" },
  { id: 327, term: "corner recovery ×", tier: "strong", category: "skill" },
  { id: 328, term: "beeline burst", tier: "strong", category: "skill" },
  { id: 329, term: "straightaway adept", tier: "strong", category: "skill" },
  { id: 330, term: "rushing gale!", tier: "strong", category: "skill" },
  { id: 331, term: "straightaway acceleration", tier: "strong", category: "skill" },
  { id: 332, term: "breath of fresh air", tier: "strong", category: "skill" },
  { id: 333, term: "straightaway recovery", tier: "strong", category: "skill" },
  { id: 334, term: "ramp revulsion", tier: "strong", category: "skill" },
  { id: 335, term: "packphobia", tier: "strong", category: "skill" },
  { id: 336, term: "defeatist", tier: "strong", category: "skill" },
  { id: 337, term: "reckless", tier: "strong", category: "skill" },
  { id: 338, term: "concentration", tier: "strong", category: "skill" },
  { id: 339, term: "focus", tier: "strong", category: "skill" },
  { id: 340, term: "gatekept", tier: "strong", category: "skill" },
  { id: 341, term: "iron will", tier: "strong", category: "skill" },
  { id: 342, term: "lay low", tier: "strong", category: "skill" },
  { id: 343, term: "center stage", tier: "strong", category: "skill" },
  { id: 344, term: "prudent positioning", tier: "strong", category: "skill" },
  { id: 345, term: "it's on!", tier: "strong", category: "skill" },
  { id: 346, term: "ramp up", tier: "strong", category: "skill" },
  { id: 347, term: "indomitable", tier: "strong", category: "skill" },
  { id: 348, term: "pace strategy", tier: "strong", category: "skill" },
  { id: 349, term: "unruffled", tier: "strong", category: "skill" },
  { id: 350, term: "calm in a crowd", tier: "strong", category: "skill" },
  { id: 351, term: "no stopping me!", tier: "strong", category: "skill" },
  { id: 352, term: "nimble navigator", tier: "strong", category: "skill" },
  { id: 353, term: "lane legerdemain", tier: "strong", category: "skill" },
  { id: 354, term: "go with the flow", tier: "strong", category: "skill" },
  { id: 355, term: "in body and mind", tier: "strong", category: "skill" },
  { id: 356, term: "homestretch haste", tier: "strong", category: "skill" },
  { id: 357, term: "running idle", tier: "strong", category: "skill" },
  { id: 358, term: "taking the lead", tier: "strong", category: "skill" },
  { id: 359, term: "early lead", tier: "strong", category: "skill" },
  { id: 360, term: "escape artist", tier: "strong", category: "skill" },
  { id: 361, term: "fast-paced", tier: "strong", category: "skill" },
  { id: 362, term: "unrestrained", tier: "strong", category: "skill" },
  { id: 363, term: "final push", tier: "strong", category: "skill" },
  { id: 364, term: "calm and collected", tier: "strong", category: "skill" },
  { id: 365, term: "stamina to spare", tier: "strong", category: "skill" },
  { id: 366, term: "race planner", tier: "strong", category: "skill" },
  { id: 367, term: "preferred position", tier: "strong", category: "skill" },
  { id: 368, term: "speed star", tier: "strong", category: "skill" },
  { id: 369, term: "prepared to pass", tier: "strong", category: "skill" },
  { id: 370, term: "fast & furious", tier: "strong", category: "skill" },
  { id: 371, term: "position pilfer", tier: "strong", category: "skill" },
  { id: 372, term: "on your left!", tier: "strong", category: "skill" },
  { id: 373, term: "slick surge", tier: "strong", category: "skill" },
  { id: 374, term: "rising dragon", tier: "strong", category: "skill" },
  { id: 375, term: "outer swell", tier: "strong", category: "skill" },
  { id: 376, term: "sleeping lion", tier: "strong", category: "skill" },
  { id: 377, term: "standing by", tier: "strong", category: "skill" },
  { id: 378, term: "sturm und drang", tier: "strong", category: "skill" },
  { id: 379, term: "masterful gambit", tier: "strong", category: "skill" },
  { id: 380, term: "encroaching shadow", tier: "strong", category: "skill" },
  { id: 381, term: "straightaway spurt", tier: "strong", category: "skill" },
  { id: 382, term: "turbo sprint", tier: "strong", category: "skill" },
  { id: 383, term: "sprinting gear", tier: "strong", category: "skill" },
  { id: 384, term: "wait-and-see", tier: "strong", category: "skill" },
  { id: 385, term: "blinding flash", tier: "strong", category: "skill" },
  { id: 386, term: "gap closer", tier: "strong", category: "skill" },
  { id: 387, term: "mile maven", tier: "strong", category: "skill" },
  { id: 388, term: "productive plan", tier: "strong", category: "skill" },
  { id: 389, term: "keen eye", tier: "strong", category: "skill" },
  { id: 390, term: "watchful eye", tier: "strong", category: "skill" },
  { id: 391, term: "furious feat", tier: "strong", category: "skill" },
  { id: 392, term: "updrafters", tier: "strong", category: "skill" },
  { id: 393, term: "rosy outlook", tier: "strong", category: "skill" },
  { id: 394, term: "killer tunes", tier: "strong", category: "skill" },
  { id: 395, term: "up-tempo", tier: "strong", category: "skill" },
  { id: 396, term: "unyielding", tier: "strong", category: "skill" },
  { id: 397, term: "steadfast", tier: "strong", category: "skill" },
  { id: 398, term: "cooldown", tier: "strong", category: "skill" },
  { id: 399, term: "deep breaths", tier: "strong", category: "skill" },
  { id: 400, term: "innate experience", tier: "strong", category: "skill" },
  { id: 401, term: "inside scoop", tier: "strong", category: "skill" },
  { id: 402, term: "adrenaline rush", tier: "strong", category: "skill" },
  { id: 403, term: "extra tank", tier: "strong", category: "skill" },
  { id: 404, term: "trick (front)", tier: "strong", category: "skill" },
  { id: 405, term: "tantalizing trick", tier: "strong", category: "skill" },
  { id: 406, term: "trick (rear)", tier: "strong", category: "skill" },
  { id: 407, term: "frenzied front runners", tier: "strong", category: "skill" },
  { id: 408, term: "frenzied pace chasers", tier: "strong", category: "skill" },
  { id: 409, term: "frenzied late surgers", tier: "strong", category: "skill" },
  { id: 410, term: "frenzied end closers", tier: "strong", category: "skill" },
  { id: 411, term: "subdued front runners", tier: "strong", category: "skill" },
  { id: 412, term: "flustered front runners", tier: "strong", category: "skill" },
  { id: 413, term: "hesitant front runners", tier: "strong", category: "skill" },
  { id: 414, term: "subdued pace chasers", tier: "strong", category: "skill" },
  { id: 415, term: "flustered pace chasers", tier: "strong", category: "skill" },
  { id: 416, term: "hesitant pace chasers", tier: "strong", category: "skill" },
  { id: 417, term: "subdued late surgers", tier: "strong", category: "skill" },
  { id: 418, term: "flustered late surgers", tier: "strong", category: "skill" },
  { id: 419, term: "hesitant late surgers", tier: "strong", category: "skill" },
  { id: 420, term: "subdued end closers", tier: "strong", category: "skill" },
  { id: 421, term: "flustered end closers", tier: "strong", category: "skill" },
  { id: 422, term: "hesitant end closers", tier: "strong", category: "skill" },
  { id: 423, term: "oi racecourse ◎", tier: "strong", category: "skill" },
  { id: 424, term: "oi racecourse ○", tier: "strong", category: "skill" },
  { id: 425, term: "oi racecourse ×", tier: "strong", category: "skill" },
  { id: 426, term: "sprint straightaways ◎", tier: "strong", category: "skill" },
  { id: 427, term: "sprint straightaways ○", tier: "strong", category: "skill" },
  { id: 428, term: "shocking flash", tier: "strong", category: "skill" },
  { id: 429, term: "sprint corners ◎", tier: "strong", category: "skill" },
  { id: 430, term: "sprint corners ○", tier: "strong", category: "skill" },
  { id: 431, term: "staggering lead", tier: "strong", category: "skill" },
  { id: 432, term: "huge lead", tier: "strong", category: "skill" },
  { id: 433, term: "plan x", tier: "strong", category: "skill" },
  { id: 434, term: "countermeasure", tier: "strong", category: "skill" },
  { id: 435, term: "perfect prep!", tier: "strong", category: "skill" },
  { id: 436, term: "meticulous measures", tier: "strong", category: "skill" },
  { id: 437, term: "adored by all", tier: "strong", category: "skill" },
  { id: 438, term: "intimidate", tier: "strong", category: "skill" },
  { id: 439, term: "you've got no shot", tier: "strong", category: "skill" },
  { id: 440, term: "stop right there!", tier: "strong", category: "skill" },
  { id: 441, term: "mile straightaways ◎", tier: "strong", category: "skill" },
  { id: 442, term: "mile straightaways ○", tier: "strong", category: "skill" },
  { id: 443, term: "mile corners ◎", tier: "strong", category: "skill" },
  { id: 444, term: "mile corners ○", tier: "strong", category: "skill" },
  { id: 445, term: "changing gears", tier: "strong", category: "skill" },
  { id: 446, term: "shifting gears", tier: "strong", category: "skill" },
  { id: 447, term: "step on the gas!", tier: "strong", category: "skill" },
  { id: 448, term: "acceleration", tier: "strong", category: "skill" },
  { id: 449, term: "big-sisterly", tier: "strong", category: "skill" },
  { id: 450, term: "unyielding spirit", tier: "strong", category: "skill" },
  { id: 451, term: "greed for speed", tier: "strong", category: "skill" },
  { id: 452, term: "speed eater", tier: "strong", category: "skill" },
  { id: 453, term: "battle formation", tier: "strong", category: "skill" },
  { id: 454, term: "opening gambit", tier: "strong", category: "skill" },
  { id: 455, term: "medium straightaways ◎", tier: "strong", category: "skill" },
  { id: 456, term: "medium straightaways ○", tier: "strong", category: "skill" },
  { id: 457, term: "flash forward", tier: "strong", category: "skill" },
  { id: 458, term: "medium corners ◎", tier: "strong", category: "skill" },
  { id: 459, term: "medium corners ○", tier: "strong", category: "skill" },
  { id: 460, term: "refraction arc", tier: "strong", category: "skill" },
  { id: 461, term: "clairvoyance", tier: "strong", category: "skill" },
  { id: 462, term: "hawkeye", tier: "strong", category: "skill" },
  { id: 463, term: "lightning step", tier: "strong", category: "skill" },
  { id: 464, term: "thunderbolt step", tier: "strong", category: "skill" },
  { id: 465, term: "miraculous step", tier: "strong", category: "skill" },
  { id: 466, term: "soft step", tier: "strong", category: "skill" },
  { id: 467, term: "dominator", tier: "strong", category: "skill" },
  { id: 468, term: "tether", tier: "strong", category: "skill" },
  { id: 469, term: "mystifying murmur", tier: "strong", category: "skill" },
  { id: 470, term: "murmur", tier: "strong", category: "skill" },
  { id: 471, term: "long straightaways ◎", tier: "strong", category: "skill" },
  { id: 472, term: "long straightaways ○", tier: "strong", category: "skill" },
  { id: 473, term: "blast forward", tier: "strong", category: "skill" },
  { id: 474, term: "long corners ◎", tier: "strong", category: "skill" },
  { id: 475, term: "long corners ○", tier: "strong", category: "skill" },
  { id: 476, term: "vanguard spirit", tier: "strong", category: "skill" },
  { id: 477, term: "keeping the lead", tier: "strong", category: "skill" },
  { id: 478, term: "vip pass", tier: "strong", category: "skill" },
  { id: 479, term: "passing pro", tier: "strong", category: "skill" },
  { id: 480, term: "overwhelming pressure", tier: "strong", category: "skill" },
  { id: 481, term: "pressure", tier: "strong", category: "skill" },
  { id: 482, term: "stamina siphon", tier: "strong", category: "skill" },
  { id: 483, term: "stamina eater", tier: "strong", category: "skill" },
  { id: 484, term: "illusionist", tier: "strong", category: "skill" },
  { id: 485, term: "smoke screen", tier: "strong", category: "skill" },
  { id: 486, term: "front runner straightaways ◎", tier: "strong", category: "skill" },
  { id: 487, term: "front runner straightaways ○", tier: "strong", category: "skill" },
  { id: 488, term: "front runner corners ◎", tier: "strong", category: "skill" },
  { id: 489, term: "front runner corners ○", tier: "strong", category: "skill" },
  { id: 490, term: "sixth sense", tier: "strong", category: "skill" },
  { id: 491, term: "dodging danger", tier: "strong", category: "skill" },
  { id: 492, term: "top runner", tier: "strong", category: "skill" },
  { id: 493, term: "leader's pride", tier: "strong", category: "skill" },
  { id: 494, term: "restless", tier: "strong", category: "skill" },
  { id: 495, term: "moxie", tier: "strong", category: "skill" },
  { id: 496, term: "reignition", tier: "strong", category: "skill" },
  { id: 497, term: "second wind", tier: "strong", category: "skill" },
  { id: 498, term: "restart", tier: "strong", category: "skill" },
  { id: 499, term: "pace chaser straightaways ◎", tier: "strong", category: "skill" },
  { id: 500, term: "pace chaser straightaways ○", tier: "strong", category: "skill" },
  { id: 501, term: "pace chaser corners ◎", tier: "strong", category: "skill" },
  { id: 502, term: "pace chaser corners ○", tier: "strong", category: "skill" },
  { id: 503, term: "technician", tier: "strong", category: "skill" },
  { id: 504, term: "shrewd step", tier: "strong", category: "skill" },
  { id: 505, term: "determined descent", tier: "strong", category: "skill" },
  { id: 506, term: "straight descent", tier: "strong", category: "skill" },
  { id: 507, term: "gourmand", tier: "strong", category: "skill" },
  { id: 508, term: "hydrate", tier: "strong", category: "skill" },
  { id: 509, term: "shatterproof", tier: "strong", category: "skill" },
  { id: 510, term: "tactical tweak", tier: "strong", category: "skill" },
  { id: 511, term: "dazzling disorientation", tier: "strong", category: "skill" },
  { id: 512, term: "disorient", tier: "strong", category: "skill" },
  { id: 513, term: "late surger straightaways ◎", tier: "strong", category: "skill" },
  { id: 514, term: "late surger straightaways ○", tier: "strong", category: "skill" },
  { id: 515, term: "late surger corners ◎", tier: "strong", category: "skill" },
  { id: 516, term: "late surger corners ○", tier: "strong", category: "skill" },
  { id: 517, term: "hard worker", tier: "strong", category: "skill" },
  { id: 518, term: "fighter", tier: "strong", category: "skill" },
  { id: 519, term: "15,000,000 cc", tier: "strong", category: "skill" },
  { id: 520, term: "1,500,000 cc", tier: "strong", category: "skill" },
  { id: 521, term: "relax", tier: "strong", category: "skill" },
  { id: 522, term: "a small breather", tier: "strong", category: "skill" },
  { id: 523, term: "the bigger picture", tier: "strong", category: "skill" },
  { id: 524, term: "studious", tier: "strong", category: "skill" },
  { id: 525, term: "all-seeing eyes", tier: "strong", category: "skill" },
  { id: 526, term: "sharp gaze", tier: "strong", category: "skill" },
  { id: 527, term: "end closer straightaways ◎", tier: "strong", category: "skill" },
  { id: 528, term: "end closer straightaways ○", tier: "strong", category: "skill" },
  { id: 529, term: "moonlit flash", tier: "strong", category: "skill" },
  { id: 530, term: "end closer corners ◎", tier: "strong", category: "skill" },
  { id: 531, term: "end closer corners ○", tier: "strong", category: "skill" },
  { id: 532, term: "the coast is clear!", tier: "strong", category: "skill" },
  { id: 533, term: "i can see right through you", tier: "strong", category: "skill" },
  { id: 534, term: "go-home specialist", tier: "strong", category: "skill" },
  { id: 535, term: "after-school stroll", tier: "strong", category: "skill" },
  { id: 536, term: "serenity", tier: "strong", category: "skill" },
  { id: 537, term: "levelheaded", tier: "strong", category: "skill" },
  { id: 538, term: "crusader", tier: "strong", category: "skill" },
  { id: 539, term: "strategist", tier: "strong", category: "skill" },
  { id: 540, term: "petrifying gaze", tier: "strong", category: "skill" },
  { id: 541, term: "intense gaze", tier: "strong", category: "skill" },
  { id: 542, term: "front runner savvy ◎", tier: "strong", category: "skill" },
  { id: 543, term: "front runner savvy ○", tier: "strong", category: "skill" },
  { id: 544, term: "pace chaser savvy ◎", tier: "strong", category: "skill" },
  { id: 545, term: "pace chaser savvy ○", tier: "strong", category: "skill" },
  { id: 546, term: "late surger savvy ◎", tier: "strong", category: "skill" },
  { id: 547, term: "late surger savvy ○", tier: "strong", category: "skill" },
  { id: 548, term: "end closer savvy ◎", tier: "strong", category: "skill" },
  { id: 549, term: "end closer savvy ○", tier: "strong", category: "skill" },
  { id: 550, term: "super lucky seven", tier: "strong", category: "skill" },
  { id: 551, term: "lucky seven", tier: "strong", category: "skill" },
  { id: 552, term: "triple 7s", tier: "strong", category: "skill" },
  { id: 553, term: "highlander", tier: "strong", category: "skill" },
  { id: 554, term: "uma stan", tier: "strong", category: "skill" },
  { id: 555, term: "superstan", tier: "strong", category: "skill" },
  { id: 556, term: "groundwork", tier: "strong", category: "skill" },
  { id: 557, term: "tail held high", tier: "strong", category: "skill" },
  { id: 558, term: "tail nine", tier: "strong", category: "skill" },
  { id: 559, term: "shake it out", tier: "strong", category: "skill" },
  { id: 560, term: "sympathy", tier: "strong", category: "skill" },
  { id: 561, term: "lone wolf", tier: "strong", category: "skill" },
  { id: 562, term: "slipstream", tier: "strong", category: "skill" },
  { id: 563, term: "perfect spot!", tier: "strong", category: "skill" },
  { id: 564, term: "playtime's over!", tier: "strong", category: "skill" },
  { id: 565, term: "see ya later!", tier: "strong", category: "skill" },
  { id: 566, term: "trending in the charts!", tier: "strong", category: "skill" },
  { id: 567, term: "top pick", tier: "strong", category: "skill" },
  { id: 568, term: "lead the charge!", tier: "strong", category: "skill" },
  { id: 569, term: "forward, march!", tier: "strong", category: "skill" },
  { id: 570, term: "lie in wait", tier: "strong", category: "skill" },
  { id: 571, term: "be still", tier: "strong", category: "skill" },
  { id: 572, term: "come what may", tier: "strong", category: "skill" },
  { id: 573, term: "all i've got", tier: "strong", category: "skill" },
  { id: 574, term: "♡ 3d nail art", tier: "strong", category: "skill" },
  { id: 575, term: "neck and neck", tier: "strong", category: "skill" },
  { id: 576, term: "head-on", tier: "strong", category: "skill" },
  { id: 577, term: "master of the sands", tier: "strong", category: "skill" },
  { id: 578, term: "familiar ground", tier: "strong", category: "skill" },
  { id: 579, term: "headliner", tier: "strong", category: "skill" },
  { id: 580, term: "feature act", tier: "strong", category: "skill" },
  { id: 581, term: "daring strike", tier: "strong", category: "skill" },
  { id: 582, term: "early start", tier: "strong", category: "skill" },
  { id: 583, term: "nothing ventured", tier: "strong", category: "skill" },
  { id: 584, term: "risky business", tier: "strong", category: "skill" },
  { id: 585, term: "in high spirits", tier: "strong", category: "skill" },
  { id: 586, term: "light as a feather", tier: "strong", category: "skill" },
  { id: 587, term: "runaway", tier: "strong", category: "skill" },
  { id: 588, term: "best in japan", tier: "strong", category: "skill" },
  { id: 589, term: "of calm mind", tier: "strong", category: "skill" },
  { id: 590, term: "free-spirited", tier: "strong", category: "skill" },
  { id: 591, term: "from the brink", tier: "strong", category: "skill" },
  { id: 592, term: "take the chance", tier: "strong", category: "skill" },
  { id: 593, term: "burning soul", tier: "strong", category: "skill" },
  { id: 594, term: "fighting spirit", tier: "strong", category: "skill" },
  { id: 595, term: "elated", tier: "strong", category: "skill" },
  { id: 596, term: "eager", tier: "strong", category: "skill" },
  { id: 597, term: "full of vigor", tier: "strong", category: "skill" },
  { id: 598, term: "pumped", tier: "strong", category: "skill" },
  { id: 599, term: "dauntless", tier: "strong", category: "skill" },
  { id: 600, term: "fearless", tier: "strong", category: "skill" },
  { id: 601, term: "wild wind", tier: "strong", category: "skill" },
  { id: 602, term: "with all my soul", tier: "strong", category: "skill" },
  { id: 603, term: "you're not the boss of me!", tier: "strong", category: "skill" },
  { id: 604, term: "keep going!", tier: "strong", category: "skill" },
  { id: 605, term: "full throttle", tier: "strong", category: "skill" },
  { id: 606, term: "restraint", tier: "strong", category: "skill" },
  { id: 607, term: "downhill speedster", tier: "strong", category: "skill" },
  { id: 608, term: "99 problems", tier: "strong", category: "skill" },
  { id: 609, term: "heart all set", tier: "strong", category: "skill" },
  { id: 610, term: "all set", tier: "strong", category: "skill" },
  { id: 611, term: "kawasaki racecourse ◎", tier: "strong", category: "skill" },
  { id: 612, term: "kawasaki racecourse ○", tier: "strong", category: "skill" },
  { id: 613, term: "kawasaki racecourse ×", tier: "strong", category: "skill" },
  { id: 614, term: "funabashi racecourse ◎", tier: "strong", category: "skill" },
  { id: 615, term: "funabashi racecourse ○", tier: "strong", category: "skill" },
  { id: 616, term: "funabashi racecourse ×", tier: "strong", category: "skill" },
  { id: 617, term: "morioka racecourse ◎", tier: "strong", category: "skill" },
  { id: 618, term: "morioka racecourse ○", tier: "strong", category: "skill" },
  { id: 619, term: "morioka racecourse ×", tier: "strong", category: "skill" },
  { id: 620, term: "night races ◎", tier: "strong", category: "skill" },
  { id: 621, term: "night races ○", tier: "strong", category: "skill" },
  { id: 622, term: "night races ×", tier: "strong", category: "skill" },
  { id: 623, term: "sharp turns ◎", tier: "strong", category: "skill" },
  { id: 624, term: "sharp turns ○", tier: "strong", category: "skill" },
  { id: 625, term: "sharp turns ×", tier: "strong", category: "skill" },
  { id: 626, term: "collaborative graded races ◎", tier: "strong", category: "skill" },
  { id: 627, term: "collaborative graded races ○", tier: "strong", category: "skill" },
  { id: 628, term: "collaborative graded races ×", tier: "strong", category: "skill" },
  { id: 629, term: "chance of victory", tier: "strong", category: "skill" },
  { id: 630, term: "sunny sign", tier: "strong", category: "skill" },
  { id: 631, term: "can't keep me down", tier: "strong", category: "skill" },
  { id: 632, term: "comeback", tier: "strong", category: "skill" },
  { id: 633, term: "full speed!", tier: "strong", category: "skill" },
  { id: 634, term: "full tilt", tier: "strong", category: "skill" },
  { id: 635, term: "crystal clear", tier: "strong", category: "skill" },
  { id: 636, term: "rational", tier: "strong", category: "skill" },
  { id: 637, term: "dancer in the dirt", tier: "strong", category: "skill" },
  { id: 638, term: "down in the dirt ○", tier: "strong", category: "skill" },
  { id: 639, term: "down in the dirt ×", tier: "strong", category: "skill" },
  { id: 640, term: "be the center!", tier: "strong", category: "skill" },
  { id: 641, term: "got the spirit!", tier: "strong", category: "skill" },
  { id: 642, term: "run like crazy!", tier: "strong", category: "skill" },
  { id: 643, term: "rapid gain", tier: "strong", category: "skill" },
  { id: 644, term: "strong steps", tier: "strong", category: "skill" },
  { id: 645, term: "solid steps", tier: "strong", category: "skill" },
  { id: 646, term: "maestro of the mud", tier: "strong", category: "skill" },
  { id: 647, term: "muddy ◎", tier: "strong", category: "skill" },
  { id: 648, term: "muddy ○", tier: "strong", category: "skill" },
  { id: 649, term: "muddy ×", tier: "strong", category: "skill" },
  { id: 650, term: "dust cloud idol", tier: "strong", category: "skill" },
  { id: 651, term: "dust cloud", tier: "strong", category: "skill" },
  { id: 652, term: "catch 'em off guard", tier: "strong", category: "skill" },
  { id: 653, term: "oppression", tier: "strong", category: "skill" },
  { id: 654, term: "unstoppable", tier: "strong", category: "skill" },
  { id: 655, term: "on the attack", tier: "strong", category: "skill" },
  { id: 656, term: "breakin' ahead", tier: "strong", category: "skill" },
  { id: 657, term: "breakin' out", tier: "strong", category: "skill" },
  { id: 658, term: "givin' it 1000%", tier: "strong", category: "skill" },
  { id: 659, term: "mad dash", tier: "strong", category: "skill" },
  { id: 660, term: "lightning surge", tier: "strong", category: "skill" },
  { id: 661, term: "leap forward", tier: "strong", category: "skill" },
  { id: 662, term: "ambitious breeze", tier: "strong", category: "skill" },
  { id: 663, term: "aspire", tier: "strong", category: "skill" },
  { id: 664, term: "claw forward", tier: "strong", category: "skill" },
  { id: 665, term: "scramble", tier: "strong", category: "skill" },
  { id: 666, term: "solid strike", tier: "strong", category: "skill" },
  { id: 667, term: "steady gait", tier: "strong", category: "skill" },
  { id: 668, term: "risk-maker", tier: "strong", category: "skill" },
  { id: 669, term: "top gear", tier: "strong", category: "skill" },
  { id: 670, term: "pedal to the metal", tier: "strong", category: "skill" },
  { id: 671, term: "can't even catch my shadow", tier: "strong", category: "skill" },
  { id: 672, term: "firm resolve", tier: "strong", category: "skill" },
  { id: 673, term: "hot pursuit", tier: "strong", category: "skill" },
  { id: 674, term: "latch on", tier: "strong", category: "skill" },
  { id: 675, term: "beast mode", tier: "strong", category: "skill" },
  { id: 676, term: "my true strength", tier: "strong", category: "skill" },
  { id: 677, term: "reckless charge", tier: "strong", category: "skill" },
  { id: 678, term: "no looking back", tier: "strong", category: "skill" },
  { id: 679, term: "burning spirit spd", tier: "strong", category: "skill" },
  { id: 680, term: "ignited spirit spd", tier: "strong", category: "skill" },
  { id: 681, term: "burning spirit sta", tier: "strong", category: "skill" },
  { id: 682, term: "ignited spirit sta", tier: "strong", category: "skill" },
  { id: 683, term: "burning spirit pwr", tier: "strong", category: "skill" },
  { id: 684, term: "ignited spirit pwr", tier: "strong", category: "skill" },
  { id: 685, term: "burning spirit guts", tier: "strong", category: "skill" },
  { id: 686, term: "ignited spirit guts", tier: "strong", category: "skill" },
  { id: 687, term: "burning spirit wit", tier: "strong", category: "skill" },
  { id: 688, term: "ignited spirit wit", tier: "strong", category: "skill" },
  { id: 689, term: "radiant star", tier: "strong", category: "skill" },
  { id: 690, term: "glittering star", tier: "strong", category: "skill" },
  { id: 691, term: "i wanna win with you", tier: "strong", category: "skill" },
  { id: 692, term: "on the way to our dream", tier: "strong", category: "skill" },
  { id: 693, term: "past my limits", tier: "strong", category: "skill" },
  { id: 694, term: "eyes on the goal", tier: "strong", category: "skill" },
  { id: 695, term: "racing spirit: speed", tier: "strong", category: "skill" },
  { id: 696, term: "racing spirit: stamina", tier: "strong", category: "skill" },
  { id: 697, term: "racing spirit: power", tier: "strong", category: "skill" },
  { id: 698, term: "racing spirit: guts", tier: "strong", category: "skill" },
  { id: 699, term: "racing spirit: wit", tier: "strong", category: "skill" },
  { id: 700, term: "racing spirit: mood", tier: "strong", category: "skill" },
  { id: 701, term: "unquenched thirst", tier: "strong", category: "skill" },
  { id: 702, term: "unchanging", tier: "strong", category: "skill" },
  { id: 703, term: "towards the scenery i seek", tier: "strong", category: "skill" },
  { id: 704, term: "creeping anxiety", tier: "strong", category: "skill" },
  { id: 705, term: "blatant fear", tier: "strong", category: "skill" },
  { id: 706, term: "dream run", tier: "strong", category: "skill" },
  { id: 707, term: "show me what lies beyond!", tier: "strong", category: "skill" },
  { id: 708, term: "hoiya! have a good run!", tier: "strong", category: "skill" },
  { id: 709, term: "as a friend and rival", tier: "strong", category: "skill" },
  { id: 710, term: "cheers of a fellow dreamer", tier: "strong", category: "skill" },
  { id: 711, term: "chin up, derby umamusume!", tier: "strong", category: "skill" },
  { id: 712, term: "for the team", tier: "strong", category: "skill" },
  { id: 713, term: "ruler of japan", tier: "strong", category: "skill" },
  { id: 714, term: "carnival bonus", tier: "strong", category: "skill" },
  { id: 715, term: "feelin' a bit silly", tier: "strong", category: "skill" },
  { id: 716, term: "medium race enthusiast", tier: "strong", category: "skill" },
  { id: 717, term: "long race enthusiast", tier: "strong", category: "skill" },
  { id: 718, term: "mile race enthusiast", tier: "strong", category: "skill" },
  { id: 720, term: "g00 1st.f∞;", tier: "strong", category: "skill" },
  { id: 721, term: "yeah☆vivid time!", tier: "strong", category: "skill" },
  { id: 722, term: "do ya breakin!", tier: "strong", category: "skill" },
  { id: 723, term: "drain for rose", tier: "strong", category: "skill" },
  { id: 724, term: "guten appetit♪", tier: "strong", category: "skill" },
  { id: 725, term: "february stakes", tier: "strong", category: "race" },
  { id: 726, term: "takamatsunomiya kinen", tier: "strong", category: "race" },
  { id: 727, term: "osaka hai", tier: "strong", category: "race" },
  { id: 728, term: "oka sho", tier: "strong", category: "race" },
  { id: 729, term: "satsuki sho", tier: "strong", category: "race" },
  { id: 730, term: "tenno sho (spring)", tier: "strong", category: "race" },
  { id: 731, term: "nhk mile cup", tier: "strong", category: "race" },
  { id: 732, term: "victoria mile", tier: "strong", category: "race" },
  { id: 733, term: "japanese oaks", tier: "strong", category: "race" },
  { id: 734, term: "tokyo yushun (japanese derby)", tier: "strong", category: "race" },
  { id: 735, term: "yasuda kinen", tier: "strong", category: "race" },
  { id: 736, term: "takarazuka kinen", tier: "strong", category: "race" },
  { id: 737, term: "sprinters stakes", tier: "strong", category: "race" },
  { id: 738, term: "shuka sho", tier: "strong", category: "race" },
  { id: 739, term: "kikuka sho", tier: "strong", category: "race" },
  { id: 740, term: "tenno sho (autumn)", tier: "strong", category: "race" },
  { id: 741, term: "queen elizabeth ii cup", tier: "strong", category: "race" },
  { id: 742, term: "mile championship", tier: "strong", category: "race" },
  { id: 743, term: "japan cup", tier: "strong", category: "race" },
  { id: 744, term: "champions cup", tier: "strong", category: "race" },
  { id: 745, term: "hanshin juvenile fillies", tier: "strong", category: "race" },
  { id: 746, term: "asahi hai futurity stakes", tier: "strong", category: "race" },
  { id: 747, term: "arima kinen", tier: "strong", category: "race" },
  { id: 748, term: "hopeful stakes", tier: "strong", category: "race" },
  { id: 749, term: "teio sho", tier: "strong", category: "race" },
  { id: 750, term: "japan dirt derby", tier: "strong", category: "race" },
  { id: 751, term: "jbc ladies’ classic", tier: "strong", category: "race" },
  { id: 752, term: "jbc sprint", tier: "strong", category: "race" },
  { id: 753, term: "jbc classic", tier: "strong", category: "race" },
  { id: 754, term: "tokyo daishoten", tier: "strong", category: "race" },
  { id: 755, term: "kawasaki kinen", tier: "strong", category: "race" },
  { id: 756, term: "zen-nippon junior yushun", tier: "strong", category: "race" },
  { id: 757, term: "kashiwa kinen", tier: "strong", category: "race" },
  { id: 758, term: "mile championship nambu hai", tier: "strong", category: "race" },
  { id: 759, term: "prix de l'arc de triomphe", tier: "strong", category: "race" },
  { id: 760, term: "japanese derby", tier: "strong", category: "race" },
  { id: 761, term: "sprinters s.", tier: "strong", category: "race" },
  { id: 762, term: "asahi hai f.s.", tier: "strong", category: "race" },
  { id: 763, term: "hanshin j.f.", tier: "strong", category: "race" },
  { id: 764, term: "champions meeting capricorn cup", tier: "strong", category: "race" },
  { id: 765, term: "champions meeting aquarius cup", tier: "strong", category: "race" },
  { id: 766, term: "champions meeting: pisces cup", tier: "strong", category: "race" },
  { id: 767, term: "champions meeting: aries cup", tier: "strong", category: "race" },
  { id: 768, term: "champions meeting: taurus cup", tier: "strong", category: "race" },
  { id: 769, term: "champions meeting: gemini cup", tier: "strong", category: "race" },
  { id: 770, term: "champions meeting: cancer cup", tier: "strong", category: "race" },
  { id: 771, term: "champions meeting: leo cup", tier: "strong", category: "race" },
  { id: 772, term: "champions meeting virgo cup", tier: "strong", category: "race" },
  { id: 773, term: "champions meeting libra cup", tier: "strong", category: "race" },
  { id: 774, term: "champions meeting scorpio cup", tier: "strong", category: "race" },
  { id: 775, term: "champions meeting sagittarius cup", tier: "strong", category: "race" },
  { id: 776, term: "champions meeting capricorn cup finals", tier: "strong", category: "race" },
  { id: 777, term: "champions meeting aquarius cup finals", tier: "strong", category: "race" },
  { id: 778, term: "champions meeting: pisces cup finals", tier: "strong", category: "race" },
  { id: 779, term: "champions meeting: aries cup finals", tier: "strong", category: "race" },
  { id: 780, term: "champions meeting: taurus cup finals", tier: "strong", category: "race" },
  { id: 781, term: "champions meeting: gemini cup finals", tier: "strong", category: "race" },
  { id: 782, term: "champions meeting: cancer cup finals", tier: "strong", category: "race" },
  { id: 783, term: "champions meeting: leo cup finals", tier: "strong", category: "race" },
  { id: 784, term: "champions meeting virgo cup finals", tier: "strong", category: "race" },
  { id: 785, term: "champions meeting libra cup finals", tier: "strong", category: "race" },
  { id: 786, term: "champions meeting scorpio cup finals", tier: "strong", category: "race" },
  { id: 787, term: "champions meeting sagittarius cup finals", tier: "strong", category: "race" },
  { id: 788, term: "virgo cup finals", tier: "strong", category: "race" },
  { id: 836, term: "nikkei shinshun hai", tier: "strong", category: "race" },
  { id: 837, term: "tokai stakes", tier: "strong", category: "race" },
  { id: 838, term: "american jcc", tier: "strong", category: "race" },
  { id: 839, term: "kyoto kinen", tier: "strong", category: "race" },
  { id: 840, term: "nakayama kinen", tier: "strong", category: "race" },
  { id: 841, term: "yayoi sho", tier: "strong", category: "race" },
  { id: 842, term: "kinko sho", tier: "strong", category: "race" },
  { id: 843, term: "fillies' revue", tier: "strong", category: "race" },
  { id: 844, term: "hanshin daishoten", tier: "strong", category: "race" },
  { id: 845, term: "spring stakes", tier: "strong", category: "race" },
  { id: 846, term: "nikkei sho", tier: "strong", category: "race" },
  { id: 847, term: "hanshin umamusume stakes", tier: "strong", category: "race" },
  { id: 848, term: "new zealand trophy", tier: "strong", category: "race" },
  { id: 849, term: "milers cup", tier: "strong", category: "race" },
  { id: 850, term: "flora stakes", tier: "strong", category: "race" },
  { id: 851, term: "aoba sho", tier: "strong", category: "race" },
  { id: 852, term: "kyoto shimbun hai", tier: "strong", category: "race" },
  { id: 853, term: "keio hai spring cup", tier: "strong", category: "race" },
  { id: 854, term: "meguro kinen", tier: "strong", category: "race" },
  { id: 855, term: "sapporo kinen", tier: "strong", category: "race" },
  { id: 856, term: "centaur stakes", tier: "strong", category: "race" },
  { id: 857, term: "rose stakes", tier: "strong", category: "race" },
  { id: 858, term: "st. lite kinen", tier: "strong", category: "race" },
  { id: 859, term: "kobe shimbun hai", tier: "strong", category: "race" },
  { id: 860, term: "all comers", tier: "strong", category: "race" },
  { id: 861, term: "mainichi okan", tier: "strong", category: "race" },
  { id: 862, term: "kyoto daishoten", tier: "strong", category: "race" },
  { id: 863, term: "fuchu umamusume stakes", tier: "strong", category: "race" },
  { id: 864, term: "swan stakes", tier: "strong", category: "race" },
  { id: 865, term: "keio hai junior stakes", tier: "strong", category: "race" },
  { id: 866, term: "copa republica argentina", tier: "strong", category: "race" },
  { id: 867, term: "daily hai junior stakes", tier: "strong", category: "race" },
  { id: 868, term: "stayers stakes", tier: "strong", category: "race" },
  { id: 869, term: "hanshin cup", tier: "strong", category: "race" },
  { id: 870, term: "ladies' prelude", tier: "strong", category: "race" },
  { id: 871, term: "tokyo hai", tier: "strong", category: "race" },
  { id: 872, term: "empress hai", tier: "strong", category: "race" },
  { id: 873, term: "kanto oaks", tier: "strong", category: "race" },
  { id: 874, term: "diolite kinen", tier: "strong", category: "race" },
  { id: 875, term: "sazanka tv hai", tier: "strong", category: "race" },
  { id: 876, term: "tulip sho", tier: "strong", category: "race" },
  { id: 877, term: "fuji stakes", tier: "strong", category: "race" },
  { id: 879, term: "kyoto kimpai", tier: "strong", category: "race" },
  { id: 880, term: "nakayama kimpai", tier: "strong", category: "race" },
  { id: 881, term: "shinzan kinen", tier: "strong", category: "race" },
  { id: 882, term: "fairy stakes", tier: "strong", category: "race" },
  { id: 883, term: "aichi hai", tier: "strong", category: "race" },
  { id: 884, term: "keisei hai", tier: "strong", category: "race" },
  { id: 885, term: "silk road stakes", tier: "strong", category: "race" },
  { id: 886, term: "negishi stakes", tier: "strong", category: "race" },
  { id: 887, term: "kisaragi sho", tier: "strong", category: "race" },
  { id: 888, term: "tokyo shimbun hai", tier: "strong", category: "race" },
  { id: 889, term: "queen cup", tier: "strong", category: "race" },
  { id: 890, term: "kyodo news hai", tier: "strong", category: "race" },
  { id: 891, term: "kyoto umamusume stakes", tier: "strong", category: "race" },
  { id: 892, term: "diamond stakes", tier: "strong", category: "race" },
  { id: 893, term: "kokura daishoten", tier: "strong", category: "race" },
  { id: 894, term: "arlington cup", tier: "strong", category: "race" },
  { id: 895, term: "hankyu hai", tier: "strong", category: "race" },
  { id: 896, term: "ocean stakes", tier: "strong", category: "race" },
  { id: 897, term: "nakayama umamusume stakes", tier: "strong", category: "race" },
  { id: 898, term: "falcon stakes", tier: "strong", category: "race" },
  { id: 899, term: "flower cup", tier: "strong", category: "race" },
  { id: 900, term: "mainichi hai", tier: "strong", category: "race" },
  { id: 901, term: "march stakes", tier: "strong", category: "race" },
  { id: 902, term: "lord derby challenge trophy", tier: "strong", category: "race" },
  { id: 903, term: "antares stakes", tier: "strong", category: "race" },
  { id: 904, term: "fukushima umamusume stakes", tier: "strong", category: "race" },
  { id: 905, term: "niigata daishoten", tier: "strong", category: "race" },
  { id: 906, term: "heian stakes", tier: "strong", category: "race" },
  { id: 907, term: "naruo kinen", tier: "strong", category: "race" },
  { id: 908, term: "mermaid stakes", tier: "strong", category: "race" },
  { id: 909, term: "epsom cup", tier: "strong", category: "race" },
  { id: 910, term: "unicorn stakes", tier: "strong", category: "race" },
  { id: 911, term: "hakodate sprint stakes", tier: "strong", category: "race" },
  { id: 912, term: "cbc sho", tier: "strong", category: "race" },
  { id: 913, term: "radio nikkei sho", tier: "strong", category: "race" },
  { id: 914, term: "procyon stakes", tier: "strong", category: "race" },
  { id: 915, term: "tanabata sho", tier: "strong", category: "race" },
  { id: 916, term: "hakodate kinen", tier: "strong", category: "race" },
  { id: 917, term: "chukyo kinen", tier: "strong", category: "race" },
  { id: 918, term: "hakodate junior stakes", tier: "strong", category: "race" },
  { id: 919, term: "ibis summer dash", tier: "strong", category: "race" },
  { id: 920, term: "queen stakes", tier: "strong", category: "race" },
  { id: 921, term: "kokura kinen", tier: "strong", category: "race" },
  { id: 922, term: "leopard stakes", tier: "strong", category: "race" },
  { id: 923, term: "sekiya kinen", tier: "strong", category: "race" },
  { id: 924, term: "elm stakes", tier: "strong", category: "race" },
  { id: 925, term: "kitakyushu kinen", tier: "strong", category: "race" },
  { id: 926, term: "niigata junior stakes", tier: "strong", category: "race" },
  { id: 927, term: "keeneland cup", tier: "strong", category: "race" },
  { id: 928, term: "sapporo junior stakes", tier: "strong", category: "race" },
  { id: 929, term: "kokura junior stakes", tier: "strong", category: "race" },
  { id: 930, term: "niigata kinen", tier: "strong", category: "race" },
  { id: 931, term: "shion stakes", tier: "strong", category: "race" },
  { id: 932, term: "keisei hai autumn handicap", tier: "strong", category: "race" },
  { id: 933, term: "sirius stakes", tier: "strong", category: "race" },
  { id: 934, term: "saudi arabia royal cup", tier: "strong", category: "race" },
  { id: 935, term: "artemis stakes", tier: "strong", category: "race" },
  { id: 936, term: "fantasy stakes", tier: "strong", category: "race" },
  { id: 937, term: "miyako stakes", tier: "strong", category: "race" },
  { id: 938, term: "musashino stakes", tier: "strong", category: "race" },
  { id: 939, term: "fukushima kinen", tier: "strong", category: "race" },
  { id: 940, term: "tokyo sports hai junior stakes", tier: "strong", category: "race" },
  { id: 941, term: "kyoto junior stakes", tier: "strong", category: "race" },
  { id: 942, term: "keihan hai", tier: "strong", category: "race" },
  { id: 943, term: "challenge cup", tier: "strong", category: "race" },
  { id: 944, term: "chunichi shimbun hai", tier: "strong", category: "race" },
  { id: 945, term: "capella stakes", tier: "strong", category: "race" },
  { id: 946, term: "turquoise stakes", tier: "strong", category: "race" },
  { id: 947, term: "tck jo-o hai", tier: "strong", category: "race" },
  { id: 948, term: "tokyo sprint", tier: "strong", category: "race" },
  { id: 949, term: "sparking lady cup", tier: "strong", category: "race" },
  { id: 950, term: "marine cup", tier: "strong", category: "race" },
  { id: 951, term: "queen sho", tier: "strong", category: "race" },
  { id: 952, term: "mercury cup", tier: "strong", category: "race" },
  { id: 953, term: "cluster cup", tier: "strong", category: "race" },
  { id: 954, term: "aoi stakes", tier: "strong", category: "race" },
  { id: 955, term: "manyo stakes", tier: "strong", category: "race" },
  { id: 956, term: "junior cup", tier: "strong", category: "race" },
  { id: 957, term: "yodo tankyori stakes", tier: "strong", category: "race" },
  { id: 958, term: "pollux stakes", tier: "strong", category: "race" },
  { id: 959, term: "january stakes", tier: "strong", category: "race" },
  { id: 960, term: "new year stakes", tier: "strong", category: "race" },
  { id: 961, term: "kobai stakes", tier: "strong", category: "race" },
  { id: 962, term: "subaru stakes", tier: "strong", category: "race" },
  { id: 963, term: "wakagoma stakes", tier: "strong", category: "race" },
  { id: 964, term: "carbuncle stakes", tier: "strong", category: "race" },
  { id: 965, term: "shirafuji stakes", tier: "strong", category: "race" },
  { id: 966, term: "crocus stakes", tier: "strong", category: "race" },
  { id: 967, term: "yamato stakes", tier: "strong", category: "race" },
  { id: 968, term: "elfin stakes", tier: "strong", category: "race" },
  { id: 969, term: "rakuyo stakes", tier: "strong", category: "race" },
  { id: 970, term: "aldebaran stakes", tier: "strong", category: "race" },
  { id: 971, term: "valentine stakes", tier: "strong", category: "race" },
  { id: 972, term: "hyacinth stakes", tier: "strong", category: "race" },
  { id: 973, term: "sobu stakes", tier: "strong", category: "race" },
  { id: 974, term: "sumire stakes", tier: "strong", category: "race" },
  { id: 975, term: "osakajo stakes", tier: "strong", category: "race" },
  { id: 976, term: "polaris stakes", tier: "strong", category: "race" },
  { id: 977, term: "nigawa stakes", tier: "strong", category: "race" },
  { id: 978, term: "anemone stakes", tier: "strong", category: "race" },
  { id: 979, term: "shoryu stakes", tier: "strong", category: "race" },
  { id: 980, term: "kochi stakes", tier: "strong", category: "race" },
  { id: 981, term: "wakaba stakes", tier: "strong", category: "race" },
  { id: 982, term: "chiba stakes", tier: "strong", category: "race" },
  { id: 983, term: "rokko stakes", tier: "strong", category: "race" },
  { id: 984, term: "coral stakes", tier: "strong", category: "race" },
  { id: 985, term: "marguerite stakes", tier: "strong", category: "race" },
  { id: 986, term: "fukuryu stakes", tier: "strong", category: "race" },
  { id: 987, term: "wasurenagusa sho", tier: "strong", category: "race" },
  { id: 988, term: "keiyo stakes", tier: "strong", category: "race" },
  { id: 989, term: "shunrai stakes", tier: "strong", category: "race" },
  { id: 990, term: "fukushima mimpo hai", tier: "strong", category: "race" },
  { id: 991, term: "tachibana stakes", tier: "strong", category: "race" },
  { id: 992, term: "oasis stakes", tier: "strong", category: "race" },
  { id: 993, term: "tennozan stakes", tier: "strong", category: "race" },
  { id: 994, term: "tango stakes", tier: "strong", category: "race" },
  { id: 995, term: "sweetpea stakes", tier: "strong", category: "race" },
  { id: 996, term: "tanigawadake stakes", tier: "strong", category: "race" },
  { id: 997, term: "principal stakes", tier: "strong", category: "race" },
  { id: 998, term: "metropolitan stakes", tier: "strong", category: "race" },
  { id: 999, term: "kurama stakes", tier: "strong", category: "race" },
  { id: 1000, term: "brilliant stakes", tier: "strong", category: "race" },
  { id: 1001, term: "miyakooji stakes", tier: "strong", category: "race" },
  { id: 1002, term: "ritto stakes", tier: "strong", category: "race" },
  { id: 1003, term: "seiryu stakes", tier: "strong", category: "race" },
  { id: 1004, term: "may stakes", tier: "strong", category: "race" },
  { id: 1005, term: "hosu stakes", tier: "strong", category: "race" },
  { id: 1006, term: "idaten stakes", tier: "strong", category: "race" },
  { id: 1007, term: "shirayuri stakes", tier: "strong", category: "race" },
  { id: 1008, term: "keyaki stakes", tier: "strong", category: "race" },
  { id: 1009, term: "azuchijo stakes", tier: "strong", category: "race" },
  { id: 1010, term: "akhalteke stakes", tier: "strong", category: "race" },
  { id: 1011, term: "tempozan stakes", tier: "strong", category: "race" },
  { id: 1012, term: "yonago stakes", tier: "strong", category: "race" },
  { id: 1013, term: "onuma stakes", tier: "strong", category: "race" },
  { id: 1014, term: "paradise stakes", tier: "strong", category: "race" },
  { id: 1015, term: "tomoe sho", tier: "strong", category: "race" },
  { id: 1016, term: "marine stakes", tier: "strong", category: "race" },
  { id: 1017, term: "meitetsu hai", tier: "strong", category: "race" },
  { id: 1018, term: "chukyo junior stakes", tier: "strong", category: "race" },
  { id: 1019, term: "fukushima tv open", tier: "strong", category: "race" },
  { id: 1020, term: "dahlia sho", tier: "strong", category: "race" },
  { id: 1021, term: "sapporo nikkei open", tier: "strong", category: "race" },
  { id: 1022, term: "uhb sho", tier: "strong", category: "race" },
  { id: 1023, term: "aso stakes", tier: "strong", category: "race" },
  { id: 1024, term: "phoenix sho", tier: "strong", category: "race" },
  { id: 1025, term: "cosmos sho", tier: "strong", category: "race" },
  { id: 1026, term: "nst sho", tier: "strong", category: "race" },
  { id: 1027, term: "clover sho", tier: "strong", category: "race" },
  { id: 1028, term: "himawari sho", tier: "strong", category: "race" },
  { id: 1029, term: "bsn sho", tier: "strong", category: "race" },
  { id: 1030, term: "kokura nikkei open", tier: "strong", category: "race" },
  { id: 1031, term: "toki stakes", tier: "strong", category: "race" },
  { id: 1032, term: "tancho stakes", tier: "strong", category: "race" },
  { id: 1033, term: "suzuran sho", tier: "strong", category: "race" },
  { id: 1034, term: "enif stakes", tier: "strong", category: "race" },
  { id: 1035, term: "nojigiku stakes", tier: "strong", category: "race" },
  { id: 1036, term: "radio nippon sho", tier: "strong", category: "race" },
  { id: 1037, term: "kikyo stakes", tier: "strong", category: "race" },
  { id: 1038, term: "fuyo stakes", tier: "strong", category: "race" },
  { id: 1039, term: "canna stakes", tier: "strong", category: "race" },
  { id: 1040, term: "port island stakes", tier: "strong", category: "race" },
  { id: 1041, term: "opal stakes", tier: "strong", category: "race" },
  { id: 1042, term: "green channel cup", tier: "strong", category: "race" },
  { id: 1043, term: "momiji stakes", tier: "strong", category: "race" },
  { id: 1044, term: "october stakes", tier: "strong", category: "race" },
  { id: 1045, term: "shinetsu stakes", tier: "strong", category: "race" },
  { id: 1046, term: "ivy stakes", tier: "strong", category: "race" },
  { id: 1047, term: "muromachi stakes", tier: "strong", category: "race" },
  { id: 1048, term: "brazil cup", tier: "strong", category: "race" },
  { id: 1049, term: "hagi stakes", tier: "strong", category: "race" },
  { id: 1050, term: "cassiopeia stakes", tier: "strong", category: "race" },
  { id: 1051, term: "lumiere autumn dash", tier: "strong", category: "race" },
  { id: 1052, term: "oro cup", tier: "strong", category: "race" },
  { id: 1053, term: "fukushima junior stakes", tier: "strong", category: "race" },
  { id: 1054, term: "andromeda stakes", tier: "strong", category: "race" },
  { id: 1055, term: "shimotsuki stakes", tier: "strong", category: "race" },
  { id: 1056, term: "fukushima minyu cup", tier: "strong", category: "race" },
  { id: 1057, term: "capital stakes", tier: "strong", category: "race" },
  { id: 1058, term: "autumn leaf stakes", tier: "strong", category: "race" },
  { id: 1059, term: "lapis lazuli stakes", tier: "strong", category: "race" },
  { id: 1060, term: "shiwasu stakes", tier: "strong", category: "race" },
  { id: 1061, term: "rigel stakes", tier: "strong", category: "race" },
  { id: 1062, term: "tanzanite stakes", tier: "strong", category: "race" },
  { id: 1063, term: "december stakes", tier: "strong", category: "race" },
  { id: 1064, term: "christmas rose stakes", tier: "strong", category: "race" },
  { id: 1065, term: "galaxy stakes", tier: "strong", category: "race" },
  { id: 1066, term: "betelgeuse stakes", tier: "strong", category: "race" },
  { id: 1067, term: "kitakyushu tankyori stakes", tier: "strong", category: "race" },
  { id: 1068, term: "azumakofuji stakes", tier: "strong", category: "race" },
  { id: 1069, term: "sleipnir stakes", tier: "strong", category: "race" },
  { id: 1070, term: "sannomiya stakes", tier: "strong", category: "race" },
  { id: 1071, term: "kanetsu stakes", tier: "strong", category: "race" },
  { id: 1072, term: "nagatsuki stakes", tier: "strong", category: "race" },
  { id: 1073, term: "uzumasa stakes", tier: "strong", category: "race" },
  { id: 1074, term: "aster sho", tier: "strong", category: "race" },
  { id: 1075, term: "saffron sho", tier: "strong", category: "race" },
  { id: 1076, term: "rindo sho", tier: "strong", category: "race" },
  { id: 1077, term: "shigiku sho", tier: "strong", category: "race" },
  { id: 1078, term: "platanus sho", tier: "strong", category: "race" },
  { id: 1079, term: "nadeshiko sho", tier: "strong", category: "race" },
  { id: 1080, term: "hyakunichiso tokubetsu", tier: "strong", category: "race" },
  { id: 1081, term: "kimmokusei tokubetsu", tier: "strong", category: "race" },
  { id: 1082, term: "oxalis sho", tier: "strong", category: "race" },
  { id: 1083, term: "kigiku sho", tier: "strong", category: "race" },
  { id: 1084, term: "mochinoki sho", tier: "strong", category: "race" },
  { id: 1085, term: "akamatsu sho", tier: "strong", category: "race" },
  { id: 1086, term: "shumeigiku sho", tier: "strong", category: "race" },
  { id: 1087, term: "cattleya sho", tier: "strong", category: "race" },
  { id: 1088, term: "begonia sho", tier: "strong", category: "race" },
  { id: 1089, term: "shiragiku sho", tier: "strong", category: "race" },
  { id: 1090, term: "habotan sho", tier: "strong", category: "race" },
  { id: 1091, term: "koyamaki sho", tier: "strong", category: "race" },
  { id: 1092, term: "manryo sho", tier: "strong", category: "race" },
  { id: 1093, term: "kuromatsu sho", tier: "strong", category: "race" },
  { id: 1094, term: "erica sho", tier: "strong", category: "race" },
  { id: 1095, term: "tsuwabuki sho", tier: "strong", category: "race" },
  { id: 1096, term: "hiiragi sho", tier: "strong", category: "race" },
  { id: 1097, term: "sazanka sho", tier: "strong", category: "race" },
  { id: 1098, term: "kantsubaki sho", tier: "strong", category: "race" },
  { id: 1099, term: "senryo sho", tier: "strong", category: "race" },
  { id: 1103, term: "moonlight sho", tier: "strong", category: "race" },
  { id: 1104, term: "jupiter cup", tier: "strong", category: "race" },
  { id: 1105, term: "team stadium", tier: "strong", category: "pvp-mode" },
  { id: 1106, term: "team race", tier: "strong", category: "pvp-mode" },
  { id: 1107, term: "room match", tier: "strong", category: "pvp-mode" },
  { id: 1108, term: "channel meeting", tier: "strong", category: "pvp-mode" },
  { id: 1109, term: "arena", tier: "weak", category: "pvp-mode", note: "ambiguous: common English" },
  { id: 1110, term: "legends", tier: "weak", category: "pvp-mode", note: "ambiguous: common English" },
  { id: 1111, term: "hall of fame", tier: "weak", category: "pvp-mode", note: "ambiguous: common English" },
  { id: 1112, term: "arc", tier: "weak", category: "pvp-mode", note: "ambiguous: common English" },
  { id: 1113, term: "champions meeting capricorn cup", tier: "strong", category: "pvp-mode" },
];
